# Generated by Django 4.2.7 on 2023-11-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_authenticationmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationmethod',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
