# Generated by Django 4.2.7 on 2023-11-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_authenticationmethod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationmethod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
