# Generated by Django 4.2.7 on 2023-11-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_authenticationmethod_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_method', models.CharField(choices=[('CHOICE_1', 'Choice 1'), ('CHOICE_2', 'Choice 2')], max_length=20)),
                ('authentication_methods', models.ManyToManyField(blank=True, to='chat.authenticationmethod')),
            ],
        ),
    ]
