# Generated by Django 4.2.7 on 2023-11-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FormWithAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authentication_methods', models.ManyToManyField(blank=True, to='chat.authenticationmethod')),
                ('evaluation_methods', models.ManyToManyField(blank=True, to='chat.evaluationmethod')),
            ],
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
