# Generated by Django 4.2.7 on 2023-11-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_evaluationmethod_formwithauthentication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formwithauthentication',
            name='other_fields',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
