# Generated by Django 4.2.7 on 2023-12-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_formwithauthentication_authentication_methods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='authentication_methods',
            field=models.ManyToManyField(to='chat.authenticationmethod'),
        ),
    ]
