# Generated by Django 4.2.7 on 2023-12-01 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_poll_authentication_methods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='authentication_methods',
        ),
        migrations.AddField(
            model_name='poll',
            name='authentication_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.authenticationmethod'),
        ),
    ]
