# Generated by Django 4.2.7 on 2023-12-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_poll_authentication_methods_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='authentication_method',
        ),
        migrations.AddField(
            model_name='poll',
            name='authentication_methods',
            field=models.ManyToManyField(to='chat.authenticationmethod'),
        ),
    ]
